# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-28 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='atten_nums',
            field=models.IntegerField(default=0, verbose_name='关注数量'),
        ),
        migrations.AddField(
            model_name='user',
            name='fan_nums',
            field=models.IntegerField(default=0, verbose_name='粉丝数量'),
        ),
    ]
