# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-15 19:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='微博内容')),
                ('pra_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comments_num', models.IntegerField(default=0, verbose_name='评论数')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='发表时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
    ]
