# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-22 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20180515_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomments',
            old_name='Blog',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='userfavorite',
            old_name='Blog',
            new_name='blog',
        ),
    ]
