# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-22 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_userpraise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='blog',
            field=models.IntegerField(default=0, verbose_name='微博'),
        ),
        migrations.AlterField(
            model_name='userpraise',
            name='blog',
            field=models.IntegerField(default=0, verbose_name='微博'),
        ),
    ]
