# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20180522_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattention',
            name='attention_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atten', to=settings.AUTH_USER_MODEL, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='userattention',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
